name: PR Deploy and Audit
on: [pull_request]
jobs:
  lint and test:
    name: CI Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Run ESLint
        run: yarn run lint

      - name: Run tests
        run: yarn test

      # - name: Run build
      #   run: yarn build

      # - name: Lighthouse benchmark
      #   run: lhci collect

      # - run: lhci upload
      #   env:
      #     LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
  deploy_and_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./sub-directory
