name: CI
on: [push]
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: [10.x, 12.x, 14.x, 15.x]

      - name: Install packages
        run: yarn

      - name: Run ESLint
        run: yarn run lint

      - name: Run tests
        run: yarn test
