name: Lint, test and build
on: [pull_request]
jobs:
  eslint:
    name: CI Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Run ESLint
        run: yarn run lint

      - name: Run tests
        run: yarn test

      - name: Run build
        run: yarn build

      - name: Lighthouse benchmark
        run: yarn lighthouse
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
