name: CI
on: [push]
jobs:
  eslint:
    name: CI Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Run ESLint
        run: yarn run lint

      - name: Run tests
        run: yarn test

      - name: Run build
        run: yarn build

      - name: Lighthouse benchmark
        run: yarn lighthouse
